name: Deploy to Azure App Service

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma client
        run: yarn prisma generate
        working-directory: ./apps/web

      - name: Build packages and application
        run: yarn build --filter=web
        env:
          NEXT_TELEMETRY_DISABLED: 1
          CI: false

      - name: Prepare deployment package
        run: |
          cd apps/web
          # Clean deploy directory if exists
          rm -rf ./deploy || true
          # Create fresh deploy directory
          mkdir -p ./deploy
          # Copy the entire standalone output
          cp -r .next/standalone/* ./deploy/
          # Handle node_modules separately to avoid conflicts
          if [ -d "./deploy/node_modules" ]; then
            rm -rf ./deploy/node_modules
          fi
          # Move the web app content to root
          mv ./deploy/apps/web/* ./deploy/
          # Force remove directories
          rm -rf ./deploy/apps/web
          rm -rf ./deploy/apps
          # Copy static files
          mkdir -p ./deploy/.next
          cp -r .next/static ./deploy/.next/static
          # Copy public files
          cp -r public ./deploy/public
          # Verify structure
          echo "Final deploy directory contents:"
          ls -la ./deploy/
          echo "Checking critical files:"
          ls -la ./deploy/server.js ./deploy/node_modules/next || true
          # Ensure successful exit
          exit 0

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "smcr-test"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./apps/web/deploy
